### PR TITLE
Hello World in Java

### PR DESCRIPTION
**Pull request by shyamkanani**

### CODE REVIEW

**Comment by Pratik-Sanghani** [comment]
@shyamkanani 
Please Give Filename as per Readme.md

**Comment by shyamkanani** [comment]
@Pratik-Sanghani  Now is it ready?

**Comment by Pratik-Sanghani** [comment]
You have to change a Class name in the program. 🔢

**Comment by shyamkanani** [comment]
@Pratik-Sanghani Now? :)

**Comment by Pratik-Sanghani** [comment]
Thank You 😊

**Pull request merged**
